version: '3'

services:

  redis:
    restart: unless-stopped
    image: redis
    labels:
      - "io.portainer.accesscontrol.teams=developers"

  host:
    build:
      context: ./pdf_render

    environment:
      - PIP_INDEX_URL
      - PYTHONUNBUFFERED=1

    labels:
      - "io.portainer.accesscontrol.teams=developers"

  celery:
    build:
      context: ./pdf_render

    command: celery -A pdf_render worker -B -l info

    environment:
      - C_FORCE_ROOT=1
      - PIP_INDEX_URL

    depends_on:
      - host
      - redis

    labels:
      - "io.portainer.accesscontrol.teams=developers"

volumes:
  logs:
    labels:
      - "io.portainer.accesscontrol.teams=developers"

networks:
  default:
    labels:
      - "io.portainer.accesscontrol.teams=developers"
